project:
  type: website
  output-dir: docs

website:
  title: "quarto-website-test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: false
